### ISSUE TITLE
Passing options to Rack::UTF8Sanitizer in Rack application

### ISSUE THREAD

**Issue by mwpastore** [whitequark/rack-utf8_sanitizer#32]
Hello,

I'd like to use Rack::UTF8Sanitizer in my Rack application, but I need to add the JSON:API content type. Here's my `use` statement in `config.ru`:

```ruby
# Application-wide UTF8 sanitization
use Rack::UTF8Sanitizer,
  :additional_content_types => ['application/vnd.api+json']
```

Unfortunately, this fails with the following error message:

```
/home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-utf8_sanitizer-1.3.1/lib/rack/utf8_sanitizer.rb:10:in `initialize': wrong number of arguments (2 for 1) (ArgumentError)
	from /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:86:in `new'
	from /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:86:in `block in use'
	from /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:147:in `[]'
	from /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:147:in `block in to_app'
	from /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:147:in `each'
	from /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:147:in `inject'
	from /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:147:in `to_app'
	from config.ru:83:in `<main>'
```

It works without the options. I've tried passing the options in as a Hash but that also fails. Any suggestions?

**Comment by whitequark** [comment]
Use the `master` branch for now; it hasn't been released.

**Comment by mwpastore** [comment]
Ah, excellent. Thank you!
